apiVersion: v1
# service is used to do networking between containers
kind: Service
metadata:
  name: client-node-port
spec: # types: NodePort(for dev most of the time), clusterIP, loadbalancer,
  type: NodePort
  ports:
    - port: 3050 #for other pods to communicate with client-pod
      targetPort: 3000 # we want to forward incoming request from 3050,31515 to 3000 inside the pod
      nodePort: 31515 # this port is for to use in browser.it has to be between 30000 - 32767
  # - port: 8000 #mapping any other port
  selector:
    component: web